import type { Metadata } from "next";
import "./globals.css";
import ApplicationTemplate from "@/components/layouts/application-template";

export const metadata: Metadata = {
  title: "کلود شاپ - فروشگاه اینترنتی - ارزان ترین قیمت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className="light">
      <body>
        <ApplicationTemplate>{children}</ ApplicationTemplate>
      </body>
    </html>
  );
}
